[[redirects]]
  from = "https://jj.kerryclements.com/*"
  to = "https://jewishjourney.kerryclements.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://berakhot.kerryclements.com/*"
  to = "https://jewishjourney.kerryclements.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tefillot.kerryclements.com/*"
  to = "https://jewishjourney.kerryclements.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://jewishlearning.kerryclements.com/*"
  to = "https://jewishjourney.kerryclements.com/:splat"
  status = 301
  force = true